version: "3.9"

services:
  nav-point-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    working_dir: /app/nav-point-service
    command: ["./main"]
    depends_on:
      - database
    restart: unless-stopped

  point-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass
    working_dir: /app/point-service
    command: ["./main"]
    depends_on:
      - database
    restart: unless-stopped

  database:
    image: postgres:17.2-bookworm
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=dbname
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
