services:
  nav-point-service:
    build:
      context: .
    ports:
      - "8080:8080"
    volumes:
      - ./nav-point-service:/nav-point-service

    environment:
      - DB_HOST=database
      - DB_NAME=dbname
      - DB_USER=dbuser
      - DB_PASS=pass

    command: >
     sh -c "go run ./cmd/app/main.go"
    

    depends_on:
      - database

  database:
      image: postgres:17.2-bookworm
      environment:
        - POSTGRES_DB=dbname
        - POSTGRES_USER=dbuser
        - POSTGRES_PASSWORD=pass